# Generated by Django 3.2 on 2022-08-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220810_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
