# Generated by Django 3.2 on 2022-08-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='floats',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
    ]
