# Generated by Django 3.2 on 2022-08-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_floats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='duration',
            field=models.DurationField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='floats',
            field=models.FloatField(null=True),
        ),
    ]
