# Generated by Django 3.2 on 2022-08-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20220810_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='floats',
        ),
        migrations.AddField(
            model_name='student',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
