# Generated by Django 3.2 on 2022-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20220810_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='floats',
            field=models.FloatField(null=True),
        ),
    ]
