# Generated by Django 3.2 on 2022-08-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True, verbose_name='Department')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='Dep_Code')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('Age', models.IntegerField(null=True, verbose_name='Age')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True, verbose_name='Gender')),
                ('birthdate', models.DateField(null=True, verbose_name='DOB')),
                ('Phone', models.BigIntegerField(null=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Photo')),
                ('MotherLanguage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lang1', to='configration.language')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configration.country')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Master.department')),
                ('knownLanguage', models.ManyToManyField(to='configration.Language')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configration.state')),
            ],
            options={
                'verbose_name_plural': 'Student',
                'ordering': ('-Name',),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('Age', models.IntegerField(null=True, verbose_name='Age')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True, verbose_name='Gender')),
                ('birthdate', models.DateField(null=True, verbose_name='DOB')),
                ('Qualification', models.CharField(max_length=255, null=True, verbose_name='Qualification')),
                ('Phone', models.BigIntegerField(null=True, verbose_name='Phone')),
                ('email', models.EmailField(default='asdf@gmail.com', max_length=254, verbose_name='Email')),
                ('Language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lang', to='configration.language', verbose_name='Mother Language')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configration.country')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Master.department')),
                ('knownLanguage', models.ManyToManyField(to='configration.Language')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configration.state')),
            ],
        ),
    ]
