# Generated by Django 3.2 on 2022-08-23 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configration', '0001_initial'),
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='MotherLanguage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lang1', to='configration.language', verbose_name='Language'),
        ),
    ]
