# Generated by Django 3.2 on 2022-10-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theaterdetail', '0001_initial'),
        ('moviedetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halltype', models.CharField(choices=[('a/c', 'A/C'), ('normal', 'Normal')], max_length=100, null=True, verbose_name='HallType')),
                ('noofseats', models.IntegerField(null=True, verbose_name='NoOfSeats')),
                ('totalamount', models.FloatField(null=True, verbose_name='TotalAmount')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theaterdetail.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('dob', models.DateField(null=True, verbose_name='DOB')),
                ('age', models.CharField(max_length=20, null=True, verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20, verbose_name='Gender')),
                ('phone', models.CharField(max_length=10, null=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('ctype', models.CharField(blank=True, default='NewCustomer', max_length=100, null=True, verbose_name='CustomerType')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=50, verbose_name='PaymentType')),
                ('bookingid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingdetail.booking', verbose_name='CoustomerName')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='coustomername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingdetail.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theaterdetail.hall'),
        ),
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedetail.movie'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bookingdetail.status'),
        ),
    ]
