# Generated by Django 3.2 on 2022-10-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingdetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='bookingid',
            new_name='name',
        ),
    ]
