# Generated by Django 3.2 on 2022-10-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingdetail', '0002_rename_bookingid_payment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='coustomername',
            new_name='customername',
        ),
    ]
