# Generated by Django 3.2 on 2022-10-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingdetail', '0004_remove_booking_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customername',
            field=models.CharField(max_length=100, null=True, verbose_name='CustomerName'),
        ),
    ]
