# Generated by Django 3.2 on 2022-10-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingdetail', '0005_booking_customername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
