# Generated by Django 3.2 on 2022-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
    ]
