# Generated by Django 3.2 on 2022-08-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='Country')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lan', models.CharField(max_length=255, null=True, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='Tamil Nadu', max_length=255, null=True, verbose_name='State')),
                ('code', models.CharField(blank=True, default='TN', max_length=100, null=True, verbose_name='Code')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configration.country', verbose_name='Country')),
            ],
        ),
    ]
