# Generated by Django 3.2 on 2022-08-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Domain_Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True, verbose_name='Gender')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='D_code')),
            ],
        ),
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True, verbose_name='Gender')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('Domains', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.domains')),
            ],
        ),
        migrations.CreateModel(
            name='Hr_domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True, verbose_name='Gender')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('Domains', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.domains')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True, verbose_name='Gender')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('Domains', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.domains')),
                ('Hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.hr_domain')),
            ],
        ),
    ]
