# Generated by Django 3.2 on 2022-08-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='age',
        ),
        migrations.RemoveField(
            model_name='domains',
            name='gender',
        ),
    ]
