# Generated by Django 3.2 on 2022-08-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220817_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_domain',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True, verbose_name='Gender'),
        ),
    ]
