# Generated by Django 3.2 on 2022-10-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moviedetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('phone', models.CharField(max_length=10, null=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('movieName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedetail.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='EmployeeType')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('halltype', models.CharField(choices=[('a/c', 'A/c'), ('normal', 'Normal')], max_length=20, null=True)),
                ('totalseat', models.IntegerField(null=True, verbose_name='TotalSeats')),
                ('amountperseat', models.FloatField(null=True, verbose_name='Amountperseat')),
                ('branchid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theaterdetail.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('dob', models.DateField(null=True, verbose_name='DOB')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, verbose_name='Gender')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('aadharno', models.CharField(max_length=12, null=True, verbose_name='AadharNo')),
                ('experience', models.IntegerField(null=True, verbose_name='Experience')),
                ('accountno', models.CharField(max_length=20, null=True, verbose_name='AccountNo')),
                ('salary', models.FloatField(null=True, verbose_name='Salery')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theaterdetail.branch')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theaterdetail.role', verbose_name='Role')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='theatername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theaterdetail.theater'),
        ),
    ]
