# Generated by Django 3.2 on 2022-10-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaterdetail', '0002_alter_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='amountperseat',
        ),
    ]
