# Generated by Django 3.2 on 2022-10-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaterdetail', '0003_remove_hall_amountperseat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='movieName',
        ),
    ]
